Feature/fix logic build date (#44)
* #Fix bug parsing data in calendar

* #Fix bug parsing data in calendar

* #Fix bug parsing data in calendar

* #Fix bug parsing data in calendar

* #Fix bug parsing data in calendar

* #Fix bug parsing data in calendar

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,6 +1,10 @@
 name: Build Project
 
 on:
+  workflow_call:
+    secrets:
+      token:
+        required: true
   push:
     branches:
       - "master"
@@ -14,7 +18,7 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [macos-13]
+        os: [macos-14]
         swift: ["5.9"]
 
     steps:
@@ -22,7 +26,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Cache Swift dependencies
-        uses: actions/cache@v2
+        uses: actions/cache@v4
         with:
           path: |
             ~/.build
@@ -46,6 +50,17 @@ jobs:
         with:
           xcode-version: latest-stable
 
+      - name: Get TestResult
+        run: xcodebuild -scheme CalendarView -destination 'platform=iOS Simulator,name=iPhone 12' -resultBundlePath TestResults test
+
+      - uses: kishikawakatsumi/xcresulttool@v1
+        if: success() || failure()
+        with:
+          path: TestResults.xcresult
+          show-passed-tests: false
+          show-code-coverage: false
+          upload-bundles: never
+
       - name: Gather code coverage
         run: xcrun llvm-cov export -format="lcov" .build/debug/CalendarViewPackageTests.xctest/Contents/MacOS/CalendarViewPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov
 
@@ -56,3 +71,26 @@ jobs:
           fail_ci_if_error: fail
           files: ./coverage_report.lcov
           verbose: true
+
+      - name: Return Status Test Fail
+        if: failure()
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+          COMMENT_BODY: "#😭 Unit Test Was Failed!
+
+            See more at: ${{ github.event.pull_request.html_url }}/checks
+            "
+          PR_NUMBER: ${{ github.event.number }}
+        run: |
+          # --edit-last
+          gh pr comment $PR_NUMBER --body "$COMMENT_BODY" --edit-last || gh pr comment $PR_NUMBER --body "$COMMENT_BODY"
+
+      - name: Return Status Test Success
+        if: success()
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+          COMMENT_BODY: "# ✅ Unit Test Success! <3"
+          PR_NUMBER: ${{ github.event.number }}
+        run: |
+          # --edit-last
+          gh pr comment $PR_NUMBER --body "$COMMENT_BODY" --edit-last || gh pr comment $PR_NUMBER --body "$COMMENT_BODY"
